# Generated by Django 4.0.5 on 2022-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WpReferenciasdisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenciaunica', models.CharField(blank=True, max_length=53, null=True)),
                ('referencia', models.CharField(blank=True, max_length=11, null=True)),
                ('codcolor', models.CharField(blank=True, max_length=2, null=True)),
                ('consecutivo', models.IntegerField()),
                ('desc_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('descgrupo', models.CharField(blank=True, max_length=50, null=True)),
                ('descsubgrupo', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo', models.CharField(blank=True, max_length=2, null=True)),
                ('subgrupo', models.CharField(blank=True, max_length=5, null=True)),
                ('tiquete', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('composicion', models.CharField(blank=True, max_length=50, null=True)),
                ('colormp', models.CharField(blank=True, max_length=50, null=True)),
                ('diseño', models.CharField(blank=True, max_length=50, null=True)),
                ('concepto', models.CharField(blank=True, max_length=50, null=True)),
                ('tallas', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'wp_referenciasdisponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpFotosCatalago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenciaunica', models.CharField(blank=True, max_length=53, null=True)),
                ('ruta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
