# Generated by Django 4.0.5 on 2022-06-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_wpdisponibles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpdisponibles',
            options={'managed': False},
        ),
    ]
